export const categoryIcons = {
    "divination": "OnlinePrediction",
    "energy": "Bolt",
    "life": "EmojiNature",
    "mind": "Psychology",
    "planar": "Compare",
    "melee": "SportsKabaddi",
    "thrown": "SportsHandball",
    "projectile": "ArrowOutward",
    "athletics": "FitnessCenter",
    "interaction": "TheaterComedy",
    "lore_nature": "Nature",
    "lore_arcana": "AutoFixHigh",
    "lore_technology": "SettingsSuggest",
    "lore_social": "ConnectWithoutContact",
    "observation": "Radar"
};

export const getRequirement = (cost: number = 0) => Math.max(((cost - 1)*25)+1, 1)

export const displayText = {
    "personal": "Personal",
    "touch": "Touch",
    "ten": "10 squares",
    "twenty": "20 squares",
    "forty": "40 squares",
    "weapon_range": "Weapon's range",
    "no_duration": "No Duration",
    "one_minute": "1 Minute",
    "one_hour": "1 Hour",
    "eight_hours": "8 Hours",
    "twenty_four_hours": "24 Hours",
    "save_ends": "Save Ends",
    "create_armor": "Create Armor",
    "create_food_and_water": "Create Food and Water",
    "create_weapon": "Create Weapon",
    "dispel_power": "Dispel power",
    "water_breathing": "Water Breathing",
    "change_appearance": "Change Appearance",
    "change_form": "Change Form",
    "change_size": "Change Size",
    "shape_change": "Shape Change",
    "difficult_terrain": "Difficult Terrain",
    "solid_terrain": "Solid Terrain",
    "plus_ten_to_skill_group": "+10 To Skill Group",
    "plus_twenty_to_skill_group": "+20 To Skill Group",
    "plus_thirty_to_skill_group": "+30 To Skill Group",
    "plus_ten_to_save": "+10 To Save",
    "plus_twenty_to_save": "+20 To Save",
    "plus_thirty_to_save": "+30 To Save",
    "success_shift": "Success Shift",
    "extra_defense_action": "Extra Defense Action",
    "power_sight": "Power Sight",
    "low_light_vision": "Low Light Vision",
    "blind_sight": "Blind Sight",
    "true_seeing": "True Seeing",
    "climb_duration": "Climb Duration",
    "swim_duration": "Swim Duration",
    "climb_add_to_move": "Climb Add To Move",
    "swim_add_to_move": "Swim Add To Move",
    "water_walking": "Water Walking",
    "movement_equals_move": "Movement Equals Move",
    "movement_equals_move_plus_2": "Movement Equals Move +2",
    "movement_equals_move_plus_4": "Movement Equals Move +4",
    "shift_2": "Shift 2",
    "shift_4": "Shift 4",
    "shift_6": "Shift 6",
    "standard_attack": "Standard Attack",
    "save_vs_condition": "Save VS Condition",
    "temp_HP": "Temp HP",
    "danger": "Danger Sense",
    "elemental_bonus": "Elemental Bonus",
    "extra_weapon": "Extra Weapon",
    "lore_arcana": "Lore Arcana",
    "lore_nature": "Lore Nature",
    "lore_social": "Lore Social",
    "lore_technology": "Lore Technology",
    "combat_effect": "Combat Effect",
}
